name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write   # needed to comment on PR

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:

      # Checkout the PR branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed for full history and gitleaks

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub gitpython

      # Install Gitleaks
      - name: Install Gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/zricethezav/gitleaks/main/install.sh | bash

      # Run PR Reviewer Script
      - name: Run PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python scripts/pr_reviewer.py
